config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    
    namespace :api do
      resources :messages, only: :index, defaults: {format: 'json'}
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :groups_users
  has_many :users, through: :groups_users

  validates :name, presence: true, uniqueness: true

  def show_the_latest_message
    if (latest_message = messages.last).present?
      latest_message.content? ? latest_message.content : "*画像投稿あり"
    else
      "まだメッセージはありません。"
    end    
  end
end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages
  has_many :groups_users
  has_many :groups, through: :groups_users

  validates :password, length: { minimum: 8, message: "は最低8文字入力してください。" }, format: { with: /\A[a-z\d]+\z/i, message: "は半角英数字のみ使用可能です。" }, on: :create
  validates :email, format: { with: /\A[a-zA-Z0-9_#!$%&`'*+-{|}~^\/=?.]+@[a-zA-Z0-9][a-zA-Z0-9.-]+\z/ }
  validates :name, presence: true, uniqueness: true

  def self.search(input, id)
    return nil if input == ""
    User.where(['name LIKE ?', "%#{input}%"]).where.not(id: id).limit(10)
  end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    @messages = group.messages.includes(:user).where("id > ?", params[:id])

    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "新規グループ作成成功！"
      redirect_to "/"
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      flash[:notice] = "グループの編集に成功しました！"
      redirect_to group_messages_path(@group)
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: "メッセージ送信成功!" }
        format.json
      end
    else
      flash.now[:alert] = "メッセージを入力してください!"
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search(params[:keyword], current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to "/"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  = render 'layouts/error_messages', model: f.object
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label "チャットメンバーを追加", class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザーを入力してください", type: "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "チャットメンバー", class: 'chat-group-form__label'
    .chat-group-form__field--right

      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', group: @group

app/views/groups/index.html.haml
%html
  %head
    %meta{charset: "utf-8"}
  %body
    %div.flash-box
    %div.wrapper
      = render 'messages/side_bar'
    - if @group.present?
      = render 'messages/main_chat'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_error_messages.html.haml
- if model.errors.any?
  #error_explanation
    %h2= "#{model.errors.full_messages.count}件のエラーがあります。"
    %ul
      - model.errors.full_messages.each do |msg|
        %li
        = msg

app/views/layouts/_flash.html.haml
.notifier
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    -#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_main_chat.html.haml
.chat-main
  .main-header
    .main-header__left-box
      %h2.main-header__left-box__current-group
        = @group.name
      %ul.main-header__left-box__member-list
        Member :
        - @group.users.each do |user|
          %li.main-header__left-box__member-list__member
            = "#{user.name}　"
    =link_to edit_group_path(@group) do
      .main-header__edit-btn Edit
  .messages
    =render partial: 'messages/message', collection: @messages
  .form
    = form_for [@group, @message] do |f|
      .input-box
        = f.text_field :content, class: 'input-box__text', placeholder: "type a message"
        = f.label :image, class: 'input-box__image' do
          %i.fa.fa-image
          = f.file_field :image, class: 'input-box__image__file'
      = f.submit 'Send', class: 'submit-btn'

app/views/messages/_message.html.haml
.message(data-message-id='#{message.id}')
  .message__upper-info
    %p.message__upper-info__talker
      = message.user.name
    %p.message__upper-info__date
      = message.created_at.strftime("%Y/%m/%d %T")
  %p.message__text
    - if message.content.present?
      = message.content
    %div
      = image_tag message.image_url if message.image.present?

app/views/messages/_side_bar.html.haml
.chat-side
  .side-header
    .side-header__box
      %p.side-header__box__user-name
      = current_user.name
      %ul.side-header__box__menu
        %li.side-header__box__menu__new-group
          =link_to new_group_path do
            %i.fa.fa-edit
        %li.side-header__box__menu__edit-user
          =link_to edit_user_path(current_user) do
            %i.fa.fa-cog
  .groups
    - current_user.groups.each do |group|
      .group
        =link_to group_messages_path(group) do
          %p.group__group-name
            = group.name
          %p.group__latest-message
            = group.show_the_latest_message

app/views/messages/index.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{charset: "utf-8"}
  %body
    %div.flash-box
    %div.wrapper
      = render "side_bar"
      = render "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        = render 'layouts/error_messages', model: f.object
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'